name: deployer

on:
  workflow_call:

jobs:
  setup:
    runs-on: self-hosted
    
    steps:
      - name: test ansible
        run: ansible-playbook --version
      - name: fetch playbook definition
        uses: actions/checkout@v4
        with:
          path: playbook
          repository: vinceoa/playground-playbook

      - name: run playbook
        working-directory: playbook
        run: ansible-playbook -i inventories/local playbook.yml