name: Sample CI

on: 
  workflow_call:
    inputs:
      input1:
        required: false
        type: string
      input2:
        required: true
        type: string
    outputs:
      dockerImages:
        description: 'Docker Images available on build host'
        value: '${{ jobs.build.outputs.output1 }}, ${{jobs.build.outputs.output2}}'

jobs:
  build:
    runs-on: self-hosted

    outputs:
      output1: ${{steps.show.conclusion}}
      output2: ${{steps.greeting.outputs.message}}

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Octo Organization ${{vars.REUSEABLE_VAR}}

      - name: Show ENV
        id: show
        run: |
          env

      - id: greeting
        run: echo "{name}=Hello, ${{ inputs.input1 }}" >> $GITHUB_OUTPUT
