name: Sample CI

on: 
  workflow_call:
    inputs:
      input1:
        required: false
        type: string
      input2:
        required: false
        type: string
    outputs:
      dockerImages:
        description: 'Docker Images available on build host'
        value: '${{ jobs.build.outputs.output1 }}'

jobs:
  build:
    runs-on: self-hosted

    outputs:
      output1: ${{steps.docker_images.outcome}}

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Octo Organization

      - name: Show ENV
        run: env

      - name: docker images
        id: docker_images
        run: docker images
