name: scanning
on:
  workflow_call:

jobs:
  code-scan:
    runs-on: self-hosted
    outputs:
      output1: ${{steps.scan.conclusion}}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: scan code
        uses: anchore/scan-action@v4
        id: scan
        continue-on-error: true
        with:
          fail-build: true
          path: .
      - name: Inspect report
        run: cat ${{steps.scan.outputs.sarif}}
      - run: |
          echo Code Scan Failed
          exit 1
        if: ${{steps.scan.outcome == 'failure' }}
  

  image-scan:
    runs-on: self-hosted
    outputs:
      output1: ${{steps.scan.conclusion}}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: build/Dockerfile
          push: false
          load: true
          tags: app:latest

      - name: scan code
        uses: anchore/scan-action@v4
        id: scan
        continue-on-error: true
        with:
          fail-build: true
          image: app:latest
          severity-cutoff: critical
      - name: Inspect report
        run: cat ${{steps.scan.outputs.sarif}}
      - run: |
          echo Code Scan Failed
          exit 1
        if: ${{steps.scan.outcome == 'failure' }}
  scan:
    runs-on: self-hosted
    needs:
      - code-scan
      - image-scan

    steps:
      - name: code scan
        run: echo CodeScan ${{needs.code-scan.result}}
      - name: image scan
        run: echo ImageScan ${{needs.image-scan.result}}

  

